// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtfR8zX9zYqQrx5oPoCZJMm2fpNpq2K0Y',
    appId: '1:49825280912:web:bc1ccb225ddc4cfd5d7915',
    messagingSenderId: '49825280912',
    projectId: 'mad-location-tracker',
    authDomain: 'mad-location-tracker.firebaseapp.com',
    storageBucket: 'mad-location-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmmH6qOkwuZt44mrlln4PgjaPzmNH9zRo',
    appId: '1:49825280912:android:e2200242d704008f5d7915',
    messagingSenderId: '49825280912',
    projectId: 'mad-location-tracker',
    storageBucket: 'mad-location-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQDLEydEhkCxjEK72iCNtn7JTMHwlI6Bs',
    appId: '1:49825280912:ios:44400968b9a04aad5d7915',
    messagingSenderId: '49825280912',
    projectId: 'mad-location-tracker',
    storageBucket: 'mad-location-tracker.appspot.com',
    iosClientId: '49825280912-ikbrlnnkf5hlfsnvp1i7rp0vjoahr27p.apps.googleusercontent.com',
    iosBundleId: 'com.example.madLocationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQDLEydEhkCxjEK72iCNtn7JTMHwlI6Bs',
    appId: '1:49825280912:ios:44400968b9a04aad5d7915',
    messagingSenderId: '49825280912',
    projectId: 'mad-location-tracker',
    storageBucket: 'mad-location-tracker.appspot.com',
    iosClientId: '49825280912-ikbrlnnkf5hlfsnvp1i7rp0vjoahr27p.apps.googleusercontent.com',
    iosBundleId: 'com.example.madLocationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtfR8zX9zYqQrx5oPoCZJMm2fpNpq2K0Y',
    appId: '1:49825280912:web:1b7d78dbef76fdb85d7915',
    messagingSenderId: '49825280912',
    projectId: 'mad-location-tracker',
    authDomain: 'mad-location-tracker.firebaseapp.com',
    storageBucket: 'mad-location-tracker.appspot.com',
  );

}